docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Controllers': controllers.md
      - 'Modules': modules.md
      - 'Listeners': listeners.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: laminas-mvc-console
site_description: Laminas\Mvc\Console
repo_url: 'https://github.com/laminas/laminas-mvc-console'
